name: Deploy to Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'services/supabase-schema.sql'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: |
          echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | supabase login
      
      - name: Deploy SQL schema
        env:
          SUPABASE_PROJECT_ID: yygzsbedvtepmaniffxo
        run: |
          # Apply the SQL schema directly using the Supabase CLI
          supabase db execute --project-ref $SUPABASE_PROJECT_ID --file ./services/supabase-schema.sql
      
      - name: Verify deployment
        env:
          SUPABASE_PROJECT_ID: yygzsbedvtepmaniffxo
        run: |
          # Check if the tables were created successfully
          supabase db execute --project-ref $SUPABASE_PROJECT_ID -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';"
